/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.module.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'gradle.module.plugin.module-info' plugin.
 */
class GradleModulePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("gradle.module.plugin.module-info")

        // Verify the result
        assertNotNull(project.tasks.findByName("module-info"))
    }
}
