/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.module.plugin

import java.io.File
import java.nio.file.Files
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder

/**
 * functional test for the 'gradle.module.plugin.module-info' plugin.
 */
class GradleModuleTreePluginFunctionalTest {
    @get:Rule val tempFolder = TemporaryFolder()

    private fun getProjectDir() = tempFolder.root
    private fun getBuildFile() = getProjectDir().resolve("build.gradle")
    private fun getSettingsFile() = getProjectDir().resolve("settings.gradle")

    @Test fun `can run task`() {
        // Setup the test build
        getSettingsFile().writeText("")
        getBuildFile().writeText("""
plugins {
    id('gradle.module.plugin.module-tree')
}
""")

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("module-tree")
        runner.withProjectDir(getProjectDir())
        val result = runner.build();
        println(result.output)
        // Verify the result
        assertTrue(result.output.contains("MODULE"))
    }
}
