/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.module.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * Module plugin that outputs module tree info for a given project.
 */
class GradleModulePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("module-info") { task ->
            task.doLast {
                println("------------------------------------------------------------------------");
                println("[MODULE]\n"+ moduleInfo(project));
            }
        }
    }

    private fun moduleInfo(project: Project): String {
        val moduleBuilder = StringBuilder();
        moduleBuilder.append("name: " + project.displayName +"\n");
        moduleBuilder.append("artifactId: " + project.artifacts + "\n");
        moduleBuilder.append("groupId: " + project.group + "\n");
        moduleBuilder.append("version: " + project.version + "\n");
        moduleBuilder.append("Parent: " + project.parent + "\n");
        moduleBuilder.append("dependencies: " + project.dependencies + "\n");
        moduleBuilder.append("modules: " + project.childProjects + "\n");
        moduleBuilder.append("plugins: " + project.plugins + "\n");
        return moduleBuilder.toString();
    }
}
